export  default {
  1000: {
    sold: 'yes',
    folder: '2008 bmw 335xi',
    headline: '2008 BMW 335XI - Only 59K Miles ',
    year: '2008',
    make: 'BMW',
    model: '335 xi',
    price: '12,500',
    transmission: 'Automatic',
    miles: '59,500',
    exteriorColor: 'Blue',
    interiorColor: 'Tan',
    vin: 'WBAVD53518A010019',
    titleStatus: 'Clean',
    cylinders: '6',
    drive: '4WD',
    description: '2008 BMW 335Xi, Excellent Condition, Local Car, None Smoker, ONLY 59K Miles, Sport Package, Heated Seats, Xenon Lights, Excellent Service Records, Carfax Certified.',
  },
  1001: {
    sold: 'no',
    folder: '2014 mini cooper s',
    headline: '2014 Mini Cooper S - Only 23,000 Miles',
    year: '2014',
    make: 'Mini',
    model: 'Cooper S',
    price: '15,950',
    transmission: 'Manual',
    miles: '23,500',
    exteriorColor: 'Grey',
    interiorColor: 'Black/Grey',
    vin: 'WMWXM7C57ET969364',
    titleStatus: 'Clean',
    cylinders: '4',
    drive: 'FWD',
    description: 'Local Trade, Excellent Condition, ONLY 23500 MILES, 6-speed Manual Transmission, Fully Loaded, None Smoker, Sport PKG, Sport Seats, Heated Seats, Navigation, Xenon Lights, New tires, Panoramic Roof, carfax Certified. ',
  },
  1002: {
    sold: 'yes',
    folder: '2014 fiat 500l',
    headline: '2014 Fiat 500L Trekking - Only 14,500 Miles',
    year: '2014',
    make: 'Fiat',
    model: '500L Trekking',
    price: '10,950',
    transmission: 'Manual',
    miles: '14,500',
    exteriorColor: 'Grey',
    interiorColor: 'Black',
    vin: 'ZFBCFADH6EZ011978',
    titleStatus: 'Clean',
    cylinders: '4',
    drive: 'FWD',
    description: 'Purchased And Serviced At Fiat Of Kirkland, Full Service Records, Excellent Condition, Trekking Premier PKG Plus, Beats Audio/Sirius XM, Navigation, Panoramic roof, Back-Up Camera, Rear Park Assist, Carfax certified.',
  },
};