export  default {
  1001: {
    headline: '2007 Audi A4 2.0T Quattro All Wheel Drive 2 Owner History Premium Package Heated Seats Moonroof',
    year: '2010',
    make: 'BMW',
    model: 'M3',
    price: '49545',
    transmission: 'Automatic',
    miles: '24165',
    exteriorColor: 'BLACK',
    interiorColor: 'BLACK',
  },
  1002: {
    headline: '2007 Audi A4 2.0T Quattro All Wheel Drive 2 Owner History Premium Package Heated Seats Moonroof',
    year: '1996',
    make: 'Toyota',
    model: 'COROLLA',
    price: '9899',
    transmission: 'Automatic',
    miles: '113165',
    exteriorColor: 'SILVER',
    interiorColor: 'GRAY',
  },
  1003: {
    headline: '2007 Audi A4 2.0T Quattro All Wheel Drive 2 Owner History Premium Package Heated Seats Moonroof',
    year: '2001',
    make: 'AUDI',
    model: 'A4',
    transmission: 'Manual',
    price: '12999',
    miles: '84952',
    exteriorColor: 'BLUE',
    interiorColor: 'BLACK',
  },
  1004: {
    headline: '2007 Audi A4 2.0T Quattro All Wheel Drive 2 Owner History Premium Package Heated Seats Moonroof',
    year: '2015',
    make: 'FORD',
    model: 'EXPLORER',
    transmission: 'Automatic',
    miles: '53185',
    exteriorColor: 'BLUE',
    interiorColor: 'BLACK',
  },
  1005: {
    headline: '2007 Audi A4 2.0T Quattro All Wheel Drive 2 Owner History Premium Package Heated Seats Moonroof',
    year: '2013',
    make: 'PORSCHE',
    model: '911',
    transmission: 'PDK',
    miles: '13069',
    exteriorColor: 'BLACK',
    interiorColor: 'BLACK',
  },
};